source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EMEmojiableBtn_Example', :exclusive => true do
  pod 'EMEmojiableBtn', :path => '../'
end

target 'EMEmojiableBtn_Tests', :exclusive => true do
  pod 'EMEmojiableBtn', :path => '../'

  
end
