source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'EMEmojiableBtn_Example' do
  pod 'EMEmojiableBtn', :path => '../'
end

target 'EMEmojiableBtn_Tests' do
  pod 'EMEmojiableBtn', :path => '../'

  
end
